Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -8,6 +8,113 @@ orbs:
 # Orchestrate or schedule a set of jobs
       
 jobs:
+  lint:
+    docker:
+      - image: circleci/node:13.8.0
+    steps:
+      - checkout
+      - run:
+          name: install dependencies
+          command: |            
+            make install
+      - run:
+          name: run lint
+          command: |
+            make lint
+            
+  smoke_test:
+    docker : 
+      - image :  alpine:latest
+    steps:
+      - run:
+          name: Install dependencies
+          command: |
+            apk add --update tar gzip curl
+      - run:
+          name: Smoke Tests
+          command: |
+            if curl -s --head "http://127.0.0.1:8080" 
+                then
+            echo "Node js working!"
+            else
+              echo "Node js failed"
+            fi
+            
+  config-image:
+    machine: true
+    working_directory: ~/app
+    steps:
+      - checkout
+      - run:
+          name: Build, test and push docker image
+          command: |
+            docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PWD}
+            docker build . -t deepikakhannarbs/my-node-app:2.0
+            docker run -d --rm --name nodeapp -p 8080:8080 deepikakhannarbs/my-node-app:2.0
+            sleep 10
+            docker container ls
+            export url="http://localhost:8080"
+            export response=$(curl -s $url)
+            echo "This is response $response"
+            if [[ $response == *"NodeJS app"* ]]; then              
+             docker stop nodeapp
+            else              
+              docker stop nodeapp
+              exit 1
+            fi
+            docker push deepikakhannarbs/my-node-app:2.0
+            
+  create-cluster:
+     executor: aws-eks/python3
+     parameters:
+       cluster-name:
+         description: |
+           rm-capstone
+         type: string
+     steps:
+       - checkout
+       - aws-eks/install-aws-iam-authenticator:
+           release-tag: ''
+       - run:
+           name: Install the eksctl tool
+           command: |
+             if which eksctl > /dev/null; then
+             echo "eksctl is already installed"
+             exit 0
+             fi
+             mkdir -p eksctl_download
+             curl --silent --location --retry 5 "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C eksctl_download
+             chmod +x eksctl_download/eksctl
+             SUDO=""
+             if [ $(id -u) -ne 0 ] && which sudo > /dev/null ; then
+             SUDO="sudo"
+             fi
+             $SUDO mv eksctl_download/eksctl /usr/local/bin/
+             rmdir eksctl_download
+       - aws-eks/create-cluster:
+           cluster-name: << parameters.cluster-name >>
+           skip-kubectl-install: false
+           verbose: 3
+           node-type: t2.micro
+           nodes-max: 2
+           ssh-access: false
+           ssh-public-key: ''
+           
+  test-cluster:
+    executor: aws-eks/python3
+    parameters:
+      cluster-name:
+        description: |
+          Name of the EKS cluster
+        type: string
+    steps:
+      - kubernetes/install
+      - aws-eks/update-kubeconfig-with-authenticator:
+          cluster-name: << parameters.cluster-name >>
+      - run:
+          command: |
+            kubectl get services
+          name: Test cluster
             
           
   create-deployment:
@@ -20,11 +127,6 @@ jobs:
 
     steps:
       - checkout
-      - run:
-          name: Install dependencies
-          command: |
-            sudo apt-get install yamllint
-            yamllint deployment.yml
       - kubernetes/install
       - aws-eks/update-kubeconfig-with-authenticator:
           cluster-name: << parameters.cluster-name >>
@@ -33,9 +135,6 @@ jobs:
           get-rollout-status: true
           resource-file-path: deployment.yml
           resource-name: deployment/my-deployment
-      - run:
-          command: | 
-            kubectl get events --all-namespaces
           
   test-deployment:
     executor: aws-eks/python3
@@ -59,8 +158,28 @@ jobs:
 workflows:
   default:
     jobs:
+      - lint
+      - smoke_test:
+          requires: [lint]
+          context: Udacity
+      - config-image:
+          requires:
+            [smoke_test]
+          context: Udacity  
+      - create-cluster:
+          cluster-name: udacity-p5
+          requires:
+            [config-image]
+          context: Udacity   
+      - test-cluster:
+          cluster-name: udacity-p5
+          requires:
+            [create-cluster]
+          context: Udacity   
       - create-deployment:
           cluster-name: udacity-p5
+          requires:
+            [test-cluster]
           context: Udacity   
       - test-deployment:
           cluster-name: udacity-p5
@@ -75,4 +194,4 @@ workflows:
           requires:
              [test-deployment]
           resource-name:  deployment/my-deployment
-          context: Udacity
+          context: Udacity 
